#!/bin/sh

trap clean 0 1 2 3 6

clean() {
  rm -f Lex.hs Parse.hs *.{hi,o} Main
}

alex Lex.x || exit
happy Parse.y || exit

case "$1" in
  *.hs) ghci "$1" ;;
  *.pl) swipl "$1" ;;
  *)    runhaskell Main.hs imagine.pl ;;
esac
